### ISSUE TITLE
provide inter-app links

### ISSUE THREAD

**Issue by tmcw** [openlawdc/code-browser-app#7]
`dccode://1-1.20` and so on. see http://handleopenurl.com/

**Comment by konklone** [comment]
Android's intent system handles this stuff pretty easily. You can have an app intercept requests to particular domains and path prefixes - so for example, the Android-packaged version of the app could intercept anything to `http://dccode.org/browse/` and below, parse the URL, and do whatever.

**Comment by tmcw** [comment]
Nice, that's way more elegant than the iOS system.
